package sl.domain;
// Generated 2018-1-19 15:08:43 by Hibernate Tools 4.0.0

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

    private long    id;
    private String  name;
    private Long    higherId;
    private Boolean exist;
    private Long    lastOperator;
    private String  remark;

    public Department() {
    }

    public Department(long id, String name, Long higherId, Boolean exist,
                      Long lastOperator, String remark) {
        this.id = id;
        this.name = name;
        this.higherId = higherId;
        this.exist = exist;
        this.lastOperator = lastOperator;
        this.remark = remark;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getHigherId() {
        return this.higherId;
    }

    public void setHigherId(Long higherId) {
        this.higherId = higherId;
    }

    public Boolean getExist() {
        return this.exist;
    }

    public void setExist(Boolean exist) {
        this.exist = exist;
    }

    public Long getLastOperator() {
        return this.lastOperator;
    }

    public void setLastOperator(Long lastOperator) {
        this.lastOperator = lastOperator;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
